// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MsAcceso.Infrastructure;

#nullable disable

namespace MsAcceso.Infrastructure.Migrations.EnterpriseDb
{
    [DbContext(typeof(EnterpriseDbContext))]
    [Migration("20250114055653_initialApp")]
    partial class initialApp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MsAcceso.Domain.Tenant.CarpetasPresupuestalesTenant.CarpetaPresupuestalTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<Guid?>("Dependencia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Dependencia");

                    b.ToTable("carpetas_presupuestales", (string)null);
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.ClientesTenant.ClienteTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TipoClienteId")
                        .HasColumnType("int");

                    b.Property<int?>("TipoDocumentoId")
                        .HasColumnType("int");

                    b.Property<int?>("TipoPersonaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.EspecialidadesTenant.EspecialidadTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ProyectoTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoTenantId");

                    b.ToTable("especialidades", (string)null);
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.PartidasRecursosTenant.PartidaRecursoTenant", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("Cantidad")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Cuadrilla")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<double?>("Parcial")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<Guid>("PartidaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Precio")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<Guid>("RecursoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PartidaId");

                    b.HasIndex("RecursoId");

                    b.ToTable("partida_recurso", (string)null);
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.PartidasTenant.PartidaTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Correlativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Dependencia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Dependencia");

                    b.ToTable("partidas", (string)null);
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.PersonasJuridicasTenant.PersonaJuridicaTenant", b =>
                {
                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PersonaId");

                    b.ToTable("personas_juridicas", (string)null);
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.PersonasNaturalesTenant.PersonaNaturalTenant", b =>
                {
                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("PersonaId");

                    b.ToTable("personas_naturales", (string)null);
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.PersonasTenant.PersonaTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TipoDocumentoId")
                        .HasColumnType("int");

                    b.Property<int?>("TipoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("personas", (string)null);
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.PresupuestosEspecialidadTitulosPartidasRecursosTenant.PresupuestoEspecialidadTituloPartidaRecursoTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("Cantidad")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Cuadrilla")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<double?>("Parcial")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<double?>("Precio")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<Guid>("PresupuestoEspecialidadTituloPartidaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecursoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PresupuestoEspecialidadTituloPartidaId");

                    b.HasIndex("RecursoId");

                    b.ToTable("presupuestos_especialidad_titulos_partidas_recursos", (string)null);
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.PresupuestosEspecialidadTitulosPartidasTenant.PresupuestoEspecialidadTituloPartidaTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<Guid>("PartidaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PresupuestoEspecialidadTituloId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PartidaId");

                    b.HasIndex("PresupuestoEspecialidadTituloId");

                    b.ToTable("presupuestos_especialidad_titulos_partidas", (string)null);
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.PresupuestosEspecialidadTitulosTenant.PresupuestoEspecialidadTituloTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Correlativo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("Dependencia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EspecialidadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Nivel")
                        .HasColumnType("int");

                    b.Property<Guid?>("TituloId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Dependencia");

                    b.HasIndex("EspecialidadId");

                    b.HasIndex("TituloId");

                    b.ToTable("presupuestos_especialidad_titulos", (string)null);
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.PresupuestosTenant.PresupuestoTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<Guid?>("CarpetaPresupuestalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("DistritoId")
                        .HasColumnType("int");

                    b.Property<string>("Fecha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JornadaDiariaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("MonedaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Plazodias")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<double?>("PresupuestoBaseCD")
                        .HasColumnType("float");

                    b.Property<double?>("PresupuestoBaseDI")
                        .HasColumnType("float");

                    b.Property<double?>("PresupuestoOfertaCD")
                        .HasColumnType("float");

                    b.Property<double?>("PresupuestoOfertaDI")
                        .HasColumnType("float");

                    b.Property<int?>("ProvinciaId")
                        .HasColumnType("int");

                    b.Property<double?>("TotalPresupuestoBase")
                        .HasColumnType("float");

                    b.Property<double?>("TotalPresupuestoOferta")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CarpetaPresupuestalId");

                    b.HasIndex("ClienteId");

                    b.ToTable("presupuestos", (string)null);
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.ProyectosTenant.ProyectoTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Correlativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PresupuestoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PresupuestoId")
                        .IsUnique()
                        .HasFilter("[PresupuestoId] IS NOT NULL");

                    b.ToTable("proyectos", (string)null);
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.RecursosTenant.RecursoTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UnidadMedidaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("recursos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("60f42d2e-731b-4a48-8c5c-6fd3f9c2aaa2"),
                            Activo = true,
                            Nombre = "Capataz",
                            UnidadMedidaId = 2125
                        },
                        new
                        {
                            Id = new Guid("a4e6a78f-4b33-4388-b2f4-7eb172c82e5a"),
                            Activo = true,
                            Nombre = "Operador de maquinaria",
                            UnidadMedidaId = 2136
                        },
                        new
                        {
                            Id = new Guid("60bef5cf-7cfd-411f-aa04-849984a3bd8b"),
                            Activo = true,
                            Nombre = "Supervisor de obra",
                            UnidadMedidaId = 2136
                        },
                        new
                        {
                            Id = new Guid("e1eef79d-bee1-414d-b4d2-658d2ad843d2"),
                            Activo = true,
                            Nombre = "Técnico eléctrico",
                            UnidadMedidaId = 2134
                        },
                        new
                        {
                            Id = new Guid("1812353c-c46e-490f-9456-dfe6c764a0c4"),
                            Activo = true,
                            Nombre = "Albañil",
                            UnidadMedidaId = 2136
                        },
                        new
                        {
                            Id = new Guid("64d34d40-6deb-4a69-91f4-40758eecfee5"),
                            Activo = true,
                            Nombre = "Ayudante general",
                            UnidadMedidaId = 2136
                        },
                        new
                        {
                            Id = new Guid("0c9c1250-1b25-42cf-8b4a-1472acb908a4"),
                            Activo = true,
                            Nombre = "Cemento",
                            UnidadMedidaId = 2126
                        },
                        new
                        {
                            Id = new Guid("71407e44-372b-4707-8a78-53f38b7f052c"),
                            Activo = true,
                            Nombre = "Arena",
                            UnidadMedidaId = 2131
                        },
                        new
                        {
                            Id = new Guid("4c84bc89-5905-4c96-9223-77665bd5cc1c"),
                            Activo = true,
                            Nombre = "Grava",
                            UnidadMedidaId = 2131
                        },
                        new
                        {
                            Id = new Guid("190dd940-58cc-4abe-8482-2ca53d4cb510"),
                            Activo = true,
                            Nombre = "Bloques de concreto",
                            UnidadMedidaId = 2125
                        },
                        new
                        {
                            Id = new Guid("279a8d64-1967-4420-8c17-3a07d72e170d"),
                            Activo = true,
                            Nombre = "Ladrillos",
                            UnidadMedidaId = 2125
                        },
                        new
                        {
                            Id = new Guid("3ea028f7-45cd-4f5d-82f3-ba56e5717c24"),
                            Activo = true,
                            Nombre = "Varillas de acero",
                            UnidadMedidaId = 2132
                        },
                        new
                        {
                            Id = new Guid("ea4bb32d-df86-4295-a4d6-1af9b9413b2b"),
                            Activo = true,
                            Nombre = "Tubos de PVC",
                            UnidadMedidaId = 2132
                        },
                        new
                        {
                            Id = new Guid("2018e9b6-8fe2-4b1c-8582-b93bcb7be381"),
                            Activo = true,
                            Nombre = "Pintura",
                            UnidadMedidaId = 2129
                        },
                        new
                        {
                            Id = new Guid("3cb15773-b803-4c2c-b3a7-f025223d587c"),
                            Activo = true,
                            Nombre = "Yeso",
                            UnidadMedidaId = 2126
                        },
                        new
                        {
                            Id = new Guid("9fe99a06-4787-42f2-b875-d981a3512cd9"),
                            Activo = true,
                            Nombre = "Clavos",
                            UnidadMedidaId = 2125
                        },
                        new
                        {
                            Id = new Guid("32480dba-bc17-4868-99dd-4c9510f4fb9f"),
                            Activo = true,
                            Nombre = "Cables eléctricos",
                            UnidadMedidaId = 2132
                        },
                        new
                        {
                            Id = new Guid("bc12556d-5195-4320-ac0b-105ad5f19016"),
                            Activo = true,
                            Nombre = "Excavadora",
                            UnidadMedidaId = 2135
                        },
                        new
                        {
                            Id = new Guid("12864c2c-86ed-42f7-a47e-de419d93410d"),
                            Activo = true,
                            Nombre = "Camión de volteo",
                            UnidadMedidaId = 2139
                        },
                        new
                        {
                            Id = new Guid("f735b650-1bad-4056-aeeb-01c4b98fe5b5"),
                            Activo = true,
                            Nombre = "Compactadora",
                            UnidadMedidaId = 2135
                        },
                        new
                        {
                            Id = new Guid("561630df-f7cb-406d-8e69-a682f45b8915"),
                            Activo = true,
                            Nombre = "Taladro eléctrico",
                            UnidadMedidaId = 2135
                        },
                        new
                        {
                            Id = new Guid("a2b7c2f0-8521-4731-806f-d6ae1070cbd2"),
                            Activo = true,
                            Nombre = "Andamios",
                            UnidadMedidaId = 2125
                        },
                        new
                        {
                            Id = new Guid("9af05731-02af-4727-8a79-8a11c34f0508"),
                            Activo = true,
                            Nombre = "Martillos",
                            UnidadMedidaId = 2125
                        },
                        new
                        {
                            Id = new Guid("d8dd669c-67b3-476e-b0b0-5f3f607adac8"),
                            Activo = true,
                            Nombre = "Llaves inglesas",
                            UnidadMedidaId = 2125
                        },
                        new
                        {
                            Id = new Guid("9d650c8d-6cda-4a1b-a55a-0aae00f38994"),
                            Activo = true,
                            Nombre = "Sierra eléctrica",
                            UnidadMedidaId = 2135
                        },
                        new
                        {
                            Id = new Guid("f8345dad-4f6c-4216-8e4c-030f1c24f063"),
                            Activo = true,
                            Nombre = "Renta de camión",
                            UnidadMedidaId = 2139
                        },
                        new
                        {
                            Id = new Guid("752e5343-71a9-45d6-b171-3dc689af396b"),
                            Activo = true,
                            Nombre = "Flete de materiales",
                            UnidadMedidaId = 2139
                        },
                        new
                        {
                            Id = new Guid("ccc3647f-b096-426c-a61a-e72d532ab23c"),
                            Activo = true,
                            Nombre = "Renta de grúa",
                            UnidadMedidaId = 2135
                        },
                        new
                        {
                            Id = new Guid("0bf526c9-7aef-41c4-855f-9bdc2914fc53"),
                            Activo = true,
                            Nombre = "Transporte personal",
                            UnidadMedidaId = 2137
                        },
                        new
                        {
                            Id = new Guid("730fcba5-4f01-4ddb-b40a-de12a2cd3960"),
                            Activo = true,
                            Nombre = "Electricidad",
                            UnidadMedidaId = 2136
                        },
                        new
                        {
                            Id = new Guid("6db7b9cd-47d0-4fe8-a988-304113c44097"),
                            Activo = true,
                            Nombre = "Agua potable",
                            UnidadMedidaId = 2136
                        },
                        new
                        {
                            Id = new Guid("de64fa6b-345a-43fb-ae8b-34d9b21f0deb"),
                            Activo = true,
                            Nombre = "Gas",
                            UnidadMedidaId = 2129
                        },
                        new
                        {
                            Id = new Guid("bc8499f7-4619-4f74-8220-d61522a35a0d"),
                            Activo = true,
                            Nombre = "Alquiler de oficinas",
                            UnidadMedidaId = 2137
                        },
                        new
                        {
                            Id = new Guid("116d904e-ca56-4e21-a57c-58cb13f01ca1"),
                            Activo = true,
                            Nombre = "Consultoría técnica",
                            UnidadMedidaId = 2136
                        },
                        new
                        {
                            Id = new Guid("1c011f29-4784-4c92-b517-4fb9f9ead63a"),
                            Activo = true,
                            Nombre = "Supervisión de obra externa",
                            UnidadMedidaId = 2136
                        },
                        new
                        {
                            Id = new Guid("511dd8bd-291b-4e99-83c9-1f8d9da0afdd"),
                            Activo = true,
                            Nombre = "Seguridad en obra",
                            UnidadMedidaId = 2136
                        },
                        new
                        {
                            Id = new Guid("66866359-146f-4326-9396-dfb900967039"),
                            Activo = true,
                            Nombre = "Equipo de protección personal",
                            UnidadMedidaId = 2125
                        },
                        new
                        {
                            Id = new Guid("2c3a82ba-c35b-404f-b20a-d89a3a6abcea"),
                            Activo = true,
                            Nombre = "Polvo de mármol",
                            UnidadMedidaId = 2126
                        },
                        new
                        {
                            Id = new Guid("1b2ad3b5-1aaa-44ce-9537-ae7bce7aed05"),
                            Activo = true,
                            Nombre = "Madera para cimbra",
                            UnidadMedidaId = 2132
                        },
                        new
                        {
                            Id = new Guid("973b2d83-501f-4f78-a9e7-0e1284b2a4c6"),
                            Activo = true,
                            Nombre = "Lonas protectoras",
                            UnidadMedidaId = 2125
                        },
                        new
                        {
                            Id = new Guid("ececd90e-bce5-4b1f-8245-c37c1a9c3b90"),
                            Activo = true,
                            Nombre = "Seguro de maquinaria",
                            UnidadMedidaId = 2137
                        });
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.RolPermisosOpcionesTenant.RolPermisoOpcionTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("OpcionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RolPermisoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RolPermisoId");

                    b.ToTable("rols_permisos_opciones", (string)null);
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.RolPermisosTenant.RolPermisoTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("MenuId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RolId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("rols_permisos", (string)null);
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.RolsTenant.RolTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("rols", (string)null);
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.TitulosTenant.TituloTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("titulos", (string)null);
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.UsersTenant.UserTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("PersonaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PersonaId");

                    b.HasIndex("RolId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.CarpetasPresupuestalesTenant.CarpetaPresupuestalTenant", b =>
                {
                    b.HasOne("MsAcceso.Domain.Tenant.CarpetasPresupuestalesTenant.CarpetaPresupuestalTenant", "DependenciaModel")
                        .WithMany("CarpetasPresupuestales")
                        .HasForeignKey("Dependencia");

                    b.Navigation("DependenciaModel");
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.EspecialidadesTenant.EspecialidadTenant", b =>
                {
                    b.HasOne("MsAcceso.Domain.Tenant.ProyectosTenant.ProyectoTenant", "ProyectoTenant")
                        .WithMany("Especialidades")
                        .HasForeignKey("ProyectoTenantId");

                    b.Navigation("ProyectoTenant");
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.PartidasRecursosTenant.PartidaRecursoTenant", b =>
                {
                    b.HasOne("MsAcceso.Domain.Tenant.PartidasTenant.PartidaTenant", "Partida")
                        .WithMany("PartidasRecursos")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MsAcceso.Domain.Tenant.RecursosTenant.RecursoTenant", "Recurso")
                        .WithMany()
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partida");

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.PartidasTenant.PartidaTenant", b =>
                {
                    b.HasOne("MsAcceso.Domain.Tenant.PartidasTenant.PartidaTenant", "DependenciaModel")
                        .WithMany("Partidas")
                        .HasForeignKey("Dependencia");

                    b.Navigation("DependenciaModel");
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.PersonasJuridicasTenant.PersonaJuridicaTenant", b =>
                {
                    b.HasOne("MsAcceso.Domain.Tenant.PersonasTenant.PersonaTenant", null)
                        .WithOne("PersonaJuridica")
                        .HasForeignKey("MsAcceso.Domain.Tenant.PersonasJuridicasTenant.PersonaJuridicaTenant", "PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.PersonasNaturalesTenant.PersonaNaturalTenant", b =>
                {
                    b.HasOne("MsAcceso.Domain.Tenant.PersonasTenant.PersonaTenant", null)
                        .WithOne("PersonaNatural")
                        .HasForeignKey("MsAcceso.Domain.Tenant.PersonasNaturalesTenant.PersonaNaturalTenant", "PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.PresupuestosEspecialidadTitulosPartidasRecursosTenant.PresupuestoEspecialidadTituloPartidaRecursoTenant", b =>
                {
                    b.HasOne("MsAcceso.Domain.Tenant.PresupuestosEspecialidadTitulosPartidasTenant.PresupuestoEspecialidadTituloPartidaTenant", "PresupuestoEspecialidadTituloPartida")
                        .WithMany()
                        .HasForeignKey("PresupuestoEspecialidadTituloPartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MsAcceso.Domain.Tenant.RecursosTenant.RecursoTenant", "Recurso")
                        .WithMany("PresupuestosEspecialidadesTitulosPartidasRecursos")
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PresupuestoEspecialidadTituloPartida");

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.PresupuestosEspecialidadTitulosPartidasTenant.PresupuestoEspecialidadTituloPartidaTenant", b =>
                {
                    b.HasOne("MsAcceso.Domain.Tenant.PartidasTenant.PartidaTenant", "Partida")
                        .WithMany("PresupuestosEspecialidadesTitulosPartidas")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MsAcceso.Domain.Tenant.PresupuestosEspecialidadTitulosTenant.PresupuestoEspecialidadTituloTenant", "PresupuestoEspecialidadTitulo")
                        .WithMany("PresupuestosEspecialidadTituloPartidas")
                        .HasForeignKey("PresupuestoEspecialidadTituloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partida");

                    b.Navigation("PresupuestoEspecialidadTitulo");
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.PresupuestosEspecialidadTitulosTenant.PresupuestoEspecialidadTituloTenant", b =>
                {
                    b.HasOne("MsAcceso.Domain.Tenant.PresupuestosEspecialidadTitulosTenant.PresupuestoEspecialidadTituloTenant", "DependenciaModel")
                        .WithMany("PresupuestosEspecialidadTitulos")
                        .HasForeignKey("Dependencia");

                    b.HasOne("MsAcceso.Domain.Tenant.EspecialidadesTenant.EspecialidadTenant", "Especialidad")
                        .WithMany("PresupuestosEspecialidadTitulos")
                        .HasForeignKey("EspecialidadId");

                    b.HasOne("MsAcceso.Domain.Tenant.TitulosTenant.TituloTenant", "Titulo")
                        .WithMany("PresupuestosEspecialidadesTitulos")
                        .HasForeignKey("TituloId");

                    b.Navigation("DependenciaModel");

                    b.Navigation("Especialidad");

                    b.Navigation("Titulo");
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.PresupuestosTenant.PresupuestoTenant", b =>
                {
                    b.HasOne("MsAcceso.Domain.Tenant.CarpetasPresupuestalesTenant.CarpetaPresupuestalTenant", "CarpetaPresupuestal")
                        .WithMany()
                        .HasForeignKey("CarpetaPresupuestalId");

                    b.HasOne("MsAcceso.Domain.Tenant.ClientesTenant.ClienteTenant", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.Navigation("CarpetaPresupuestal");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.ProyectosTenant.ProyectoTenant", b =>
                {
                    b.HasOne("MsAcceso.Domain.Tenant.PresupuestosTenant.PresupuestoTenant", "Presupuesto")
                        .WithOne("ProyectoTenant")
                        .HasForeignKey("MsAcceso.Domain.Tenant.ProyectosTenant.ProyectoTenant", "PresupuestoId");

                    b.Navigation("Presupuesto");
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.RolPermisosOpcionesTenant.RolPermisoOpcionTenant", b =>
                {
                    b.HasOne("MsAcceso.Domain.Tenant.RolPermisosTenant.RolPermisoTenant", "RolPermiso")
                        .WithMany("RolPermisoOpcions")
                        .HasForeignKey("RolPermisoId");

                    b.Navigation("RolPermiso");
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.RolPermisosTenant.RolPermisoTenant", b =>
                {
                    b.HasOne("MsAcceso.Domain.Tenant.RolsTenant.RolTenant", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("RolId");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.UsersTenant.UserTenant", b =>
                {
                    b.HasOne("MsAcceso.Domain.Tenant.PersonasTenant.PersonaTenant", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId");

                    b.HasOne("MsAcceso.Domain.Tenant.RolsTenant.RolTenant", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId");

                    b.Navigation("Persona");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.CarpetasPresupuestalesTenant.CarpetaPresupuestalTenant", b =>
                {
                    b.Navigation("CarpetasPresupuestales");
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.EspecialidadesTenant.EspecialidadTenant", b =>
                {
                    b.Navigation("PresupuestosEspecialidadTitulos");
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.PartidasTenant.PartidaTenant", b =>
                {
                    b.Navigation("Partidas");

                    b.Navigation("PartidasRecursos");

                    b.Navigation("PresupuestosEspecialidadesTitulosPartidas");
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.PersonasTenant.PersonaTenant", b =>
                {
                    b.Navigation("PersonaJuridica");

                    b.Navigation("PersonaNatural");
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.PresupuestosEspecialidadTitulosTenant.PresupuestoEspecialidadTituloTenant", b =>
                {
                    b.Navigation("PresupuestosEspecialidadTituloPartidas");

                    b.Navigation("PresupuestosEspecialidadTitulos");
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.PresupuestosTenant.PresupuestoTenant", b =>
                {
                    b.Navigation("ProyectoTenant");
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.ProyectosTenant.ProyectoTenant", b =>
                {
                    b.Navigation("Especialidades");
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.RecursosTenant.RecursoTenant", b =>
                {
                    b.Navigation("PresupuestosEspecialidadesTitulosPartidasRecursos");
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.RolPermisosTenant.RolPermisoTenant", b =>
                {
                    b.Navigation("RolPermisoOpcions");
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.RolsTenant.RolTenant", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.TitulosTenant.TituloTenant", b =>
                {
                    b.Navigation("PresupuestosEspecialidadesTitulos");
                });
#pragma warning restore 612, 618
        }
    }
}
