
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MsAcceso.Domain.Root.Parametros;
using MsAcceso.Domain.Shared;

namespace MsAcceso.Infrastructure.Configurations;

internal sealed class ParametroConfiguration : IEntityTypeConfiguration<Parametro>
{
    public void Configure(
        EntityTypeBuilder<Parametro> builder
        )
    {
        builder.ToTable("parametros");
        builder.HasKey(parametro => parametro.Id);

        builder.Property(parametro => parametro.Id)
        .HasConversion(parametroId => parametroId!.Value, value => new ParametroId(value));

        builder.Property(parametro => parametro.Nombre)
        .IsRequired()
        .HasMaxLength(50);

        builder.Property(parametro => parametro.Abreviatura)
        .HasMaxLength(10);

        builder.Property(parametro => parametro.Descripcion)
        .HasMaxLength(300);

        builder.Property(parametro => parametro.Nivel)
        .IsRequired();

        builder.Property(parametro => parametro.Activo)
        .IsRequired()
        .HasConversion(estado => estado!.Value, value => new Activo(value));

        builder.Property(parametro => parametro.Valor)
        .HasMaxLength(2);

        builder.HasOne<Parametro>()
            .WithMany()
            .HasForeignKey(parametro => parametro.Dependencia);


        builder.HasData(
            Parametro.Create(new ParametroId(1), "ESTADO DE SOLICITUDES", null, null, null, 0, null),
            Parametro.Create(new ParametroId(2), "TIPO DE PERSONA", null, null, null, 0, null),
            Parametro.Create(new ParametroId(3), "NATURAL", null, null, new ParametroId(2), 1, "1"),
            Parametro.Create(new ParametroId(4), "JURIDICA", null, null, new ParametroId(2), 1, "2"),
            Parametro.Create(new ParametroId(5), "TIPO DE ASUNTO", null, null, null, 0, null),
            Parametro.Create(new ParametroId(6), "DOCUMENTO NACIONAL DE IDENTIDAD", "DNI", null, new ParametroId(3), 2, "1"),
            Parametro.Create(new ParametroId(7), "REGISTRO UNICO DE CONTRIBUYENTES", "RUC", null, new ParametroId(4), 2, "1"),
            Parametro.Create(new ParametroId(8), "CARNET DE EXTRANJERIA", "CE", null, new ParametroId(3), 2, "2"),
            Parametro.Create(new ParametroId(9), "TIPO DE ROL", null, null, null, 0, null),
            Parametro.Create(new ParametroId(10), "LICENCIA", null, null, new ParametroId(9), 1, "1"),
            Parametro.Create(new ParametroId(11), "ADMINISTRADOR", null, null, new ParametroId(9), 1, "2"),
            Parametro.Create(new ParametroId(12), "PERIODO DE LICENCIAS", null, null, null, 0, null),
            Parametro.Create(new ParametroId(13), "1 MES", null, null, new ParametroId(12), 1, "1"),
            Parametro.Create(new ParametroId(14), "6 MESES", null, null, new ParametroId(12), 1, "6"),
            Parametro.Create(new ParametroId(15), "12 MESES", null, null, new ParametroId(12), 1, "12"),
            Parametro.Create(new ParametroId(16), "TIPO DE IDENTIFICADOR SGO", null, null, null, 0, null),
            Parametro.Create(new ParametroId(17), "CLIENTE", null, null, new ParametroId(16), 1, "0"),
            Parametro.Create(new ParametroId(18), "PROVEEDOR", null, null, new ParametroId(16), 1, "1"),
            Parametro.Create(new ParametroId(19), "TIPO DE RECURSO", null, null, null, 0, null),
            Parametro.Create(new ParametroId(20), "MANO DE OBRA", null, null, new ParametroId(19), 1, "0"),
            Parametro.Create(new ParametroId(21), "SERVICIO", null, null, new ParametroId(19), 1, "1"),
            Parametro.Create(new ParametroId(22), "MATERIALES", null, null, new ParametroId(19), 1, "2"),
            Parametro.Create(new ParametroId(23), "CONTRATO", null, null, new ParametroId(19), 1, "3"),
            Parametro.Create(new ParametroId(24), "UBIGEO", null, null, null, 0, null),
            Parametro.Create(new ParametroId(25), "Amazonas", null, null, new ParametroId(24), 1, null),
            Parametro.Create(new ParametroId(26), "Áncash", null, null, new ParametroId(24), 1, null),
            Parametro.Create(new ParametroId(27), "Apurímac", null, null, new ParametroId(24), 1, null),
            Parametro.Create(new ParametroId(28), "Arequipa", null, null, new ParametroId(24), 1, null),
            Parametro.Create(new ParametroId(29), "Ayacucho", null, null, new ParametroId(24), 1, null),
            Parametro.Create(new ParametroId(30), "Cajamarca", null, null, new ParametroId(24), 1, null),
            Parametro.Create(new ParametroId(31), "Callao", null, null, new ParametroId(24), 1, null),
            Parametro.Create(new ParametroId(32), "Cusco", null, null, new ParametroId(24), 1, null),
            Parametro.Create(new ParametroId(33), "Huancavelica", null, null, new ParametroId(24), 1, null),
            Parametro.Create(new ParametroId(34), "Huánuco", null, null, new ParametroId(24), 1, null),
            Parametro.Create(new ParametroId(35), "Ica", null, null, new ParametroId(24), 1, null),
            Parametro.Create(new ParametroId(36), "Junín", null, null, new ParametroId(24), 1, null),
            Parametro.Create(new ParametroId(37), "La Libertad", null, null, new ParametroId(24), 1, null),
            Parametro.Create(new ParametroId(38), "Lambayeque", null, null, new ParametroId(24), 1, null),
            Parametro.Create(new ParametroId(39), "Lima", null, null, new ParametroId(24), 1, null),
            Parametro.Create(new ParametroId(40), "Loreto", null, null, new ParametroId(24), 1, null),
            Parametro.Create(new ParametroId(41), "Madre de Dios", null, null, new ParametroId(24), 1, null),
            Parametro.Create(new ParametroId(42), "Moquegua", null, null, new ParametroId(24), 1, null),
            Parametro.Create(new ParametroId(43), "Pasco", null, null, new ParametroId(24), 1, null),
            Parametro.Create(new ParametroId(44), "Piura", null, null, new ParametroId(24), 1, null),
            Parametro.Create(new ParametroId(45), "Puno", null, null, new ParametroId(24), 1, null),
            Parametro.Create(new ParametroId(46), "San Martín", null, null, new ParametroId(24), 1, null),
            Parametro.Create(new ParametroId(47), "Tacna", null, null, new ParametroId(24), 1, null),
            Parametro.Create(new ParametroId(48), "Tumbes", null, null, new ParametroId(24), 1, null),
            Parametro.Create(new ParametroId(49), "Ucayali", null, null, new ParametroId(24), 1, null),

            //Ucayali
            //Provincias
            Parametro.Create(new ParametroId(50), "Coronel Portillo", null, null, new ParametroId(49), 2, null),
            Parametro.Create(new ParametroId(51), "Atalaya", null, null, new ParametroId(49), 2, null),
            Parametro.Create(new ParametroId(52), "Padre Abad", null, null, new ParametroId(49), 2, null),
            Parametro.Create(new ParametroId(53), "Purús", null, null, new ParametroId(49), 2, null),
            //Distritos
            Parametro.Create(new ParametroId(54), "Callería", null, null, new ParametroId(50), 3, null),
            Parametro.Create(new ParametroId(55), "Campoverde", null, null, new ParametroId(50), 3, null),
            Parametro.Create(new ParametroId(56), "Iparía", null, null, new ParametroId(50), 3, null),
            Parametro.Create(new ParametroId(57), "Masisea", null, null, new ParametroId(50), 3, null),
            Parametro.Create(new ParametroId(58), "Yarinacocha", null, null, new ParametroId(50), 3, null),
            Parametro.Create(new ParametroId(59), "Nueva Requena", null, null, new ParametroId(50), 3, null),
            Parametro.Create(new ParametroId(60), "Manantay", null, null, new ParametroId(50), 3, null),
            Parametro.Create(new ParametroId(61), "Raymondi", null, null, new ParametroId(51), 3, null),
            Parametro.Create(new ParametroId(62), "Sepahua", null, null, new ParametroId(51), 3, null),
            Parametro.Create(new ParametroId(63), "Tahuanía", null, null, new ParametroId(51), 3, null),
            Parametro.Create(new ParametroId(64), "Yurúa", null, null, new ParametroId(51), 3, null),
            Parametro.Create(new ParametroId(65), "Padre Abad", null, null, new ParametroId(52), 3, null),
            Parametro.Create(new ParametroId(66), "Irázola", null, null, new ParametroId(52), 3, null),
            Parametro.Create(new ParametroId(67), "Curimana", null, null, new ParametroId(52), 3, null),
            Parametro.Create(new ParametroId(68), "Neshuya", null, null, new ParametroId(52), 3, null),
            Parametro.Create(new ParametroId(69), "Alexander Von Humboldt", null, null, new ParametroId(52), 3, null),
            Parametro.Create(new ParametroId(70), "Purús", null, null, new ParametroId(53), 3, null),

            //Amazonas
            //Provincias
            Parametro.Create(new ParametroId(71), "Chachapoyas", null, null, new ParametroId(25), 2, null),
            Parametro.Create(new ParametroId(72), "Bagua", null, null, new ParametroId(25), 2, null),
            Parametro.Create(new ParametroId(73), "Bongará", null, null, new ParametroId(25), 2, null),
            Parametro.Create(new ParametroId(74), "Condorcanqui", null, null, new ParametroId(25), 2, null),
            Parametro.Create(new ParametroId(75), "Luya", null, null, new ParametroId(25), 2, null),
            Parametro.Create(new ParametroId(76), "Rodríguez de Mendoza", null, null, new ParametroId(25), 2, null),
            Parametro.Create(new ParametroId(77), "Utcubamba", null, null, new ParametroId(25), 2, null),

            //Distritos
            Parametro.Create(new ParametroId(79), "Chachapoyas", null, null, new ParametroId(71), 3, null),
            Parametro.Create(new ParametroId(80), "Asunción", null, null, new ParametroId(71), 3, null),
            Parametro.Create(new ParametroId(81), "Balsas", null, null, new ParametroId(71), 3, null),
            Parametro.Create(new ParametroId(82), "Cheto", null, null, new ParametroId(71), 3, null),
            Parametro.Create(new ParametroId(83), "Chiliquin", null, null, new ParametroId(71), 3, null),
            Parametro.Create(new ParametroId(84), "Chuquibamba", null, null, new ParametroId(71), 3, null),
            Parametro.Create(new ParametroId(85), "Granada", null, null, new ParametroId(71), 3, null),
            Parametro.Create(new ParametroId(86), "Huancas", null, null, new ParametroId(71), 3, null),
            Parametro.Create(new ParametroId(87), "La Jalca", null, null, new ParametroId(71), 3, null),
            Parametro.Create(new ParametroId(88), "Leimebamba", null, null, new ParametroId(71), 3, null),
            Parametro.Create(new ParametroId(89), "Levanto", null, null, new ParametroId(71), 3, null),
            Parametro.Create(new ParametroId(90), "Magdalena", null, null, new ParametroId(71), 3, null),
            Parametro.Create(new ParametroId(91), "Mariscal Castilla", null, null, new ParametroId(71), 3, null),
            Parametro.Create(new ParametroId(92), "Molinopampa", null, null, new ParametroId(71), 3, null),
            Parametro.Create(new ParametroId(93), "Montevideo", null, null, new ParametroId(71), 3, null),
            Parametro.Create(new ParametroId(94), "Olleros", null, null, new ParametroId(71), 3, null),
            Parametro.Create(new ParametroId(95), "Quinjalca", null, null, new ParametroId(71), 3, null),
            Parametro.Create(new ParametroId(96), "San Francisco de Daguas", null, null, new ParametroId(71), 3, null),
            Parametro.Create(new ParametroId(97), "San Isidro de Maino", null, null, new ParametroId(71), 3, null),
            Parametro.Create(new ParametroId(98), "Soloco", null, null, new ParametroId(71), 3, null),
            Parametro.Create(new ParametroId(99), "Sonche", null, null, new ParametroId(71), 3, null),
            Parametro.Create(new ParametroId(100), "Bagua", null, null, new ParametroId(72), 3, null),
            Parametro.Create(new ParametroId(101), "Aramango", null, null, new ParametroId(72), 3, null),
            Parametro.Create(new ParametroId(102), "Copallin", null, null, new ParametroId(72), 3, null),
            Parametro.Create(new ParametroId(103), "El Parco", null, null, new ParametroId(72), 3, null),
            Parametro.Create(new ParametroId(104), "Imaza", null, null, new ParametroId(72), 3, null),
            Parametro.Create(new ParametroId(105), "La Peca", null, null, new ParametroId(72), 3, null),
            Parametro.Create(new ParametroId(106), "Jumbilla", null, null, new ParametroId(73), 3, null),
            Parametro.Create(new ParametroId(107), "Chisquilla", null, null, new ParametroId(73), 3, null),
            Parametro.Create(new ParametroId(108), "Churuja", null, null, new ParametroId(73), 3, null),
            Parametro.Create(new ParametroId(109), "Corosha", null, null, new ParametroId(73), 3, null),
            Parametro.Create(new ParametroId(110), "Cuispes", null, null, new ParametroId(73), 3, null),
            Parametro.Create(new ParametroId(111), "Florida", null, null, new ParametroId(73), 3, null),
            Parametro.Create(new ParametroId(112), "Jazan", null, null, new ParametroId(73), 3, null),
            Parametro.Create(new ParametroId(113), "Recta", null, null, new ParametroId(73), 3, null),
            Parametro.Create(new ParametroId(114), "San Carlos", null, null, new ParametroId(73), 3, null),
            Parametro.Create(new ParametroId(115), "Shipasbamba", null, null, new ParametroId(73), 3, null),
            Parametro.Create(new ParametroId(116), "Valera", null, null, new ParametroId(73), 3, null),
            Parametro.Create(new ParametroId(117), "Yambrasbamba", null, null, new ParametroId(73), 3, null),
            Parametro.Create(new ParametroId(118), "Nieva", null, null, new ParametroId(74), 3, null),
            Parametro.Create(new ParametroId(119), "El Cenepa", null, null, new ParametroId(74), 3, null),
            Parametro.Create(new ParametroId(120), "Río Santiago", null, null, new ParametroId(74), 3, null),
            Parametro.Create(new ParametroId(121), "Lamud", null, null, new ParametroId(75), 3, null),
            Parametro.Create(new ParametroId(122), "Camporredondo", null, null, new ParametroId(75), 3, null),
            Parametro.Create(new ParametroId(123), "Cocabamba", null, null, new ParametroId(75), 3, null),
            Parametro.Create(new ParametroId(124), "Colcamar", null, null, new ParametroId(75), 3, null),
            Parametro.Create(new ParametroId(125), "Conila", null, null, new ParametroId(75), 3, null),
            Parametro.Create(new ParametroId(126), "Inguilpata", null, null, new ParametroId(75), 3, null),
            Parametro.Create(new ParametroId(127), "Longuita", null, null, new ParametroId(75), 3, null),
            Parametro.Create(new ParametroId(128), "Lonya Chico", null, null, new ParametroId(75), 3, null),
            Parametro.Create(new ParametroId(129), "Luya", null, null, new ParametroId(75), 3, null),
            Parametro.Create(new ParametroId(130), "Luya Viejo", null, null, new ParametroId(75), 3, null),
            Parametro.Create(new ParametroId(131), "María", null, null, new ParametroId(75), 3, null),
            Parametro.Create(new ParametroId(132), "Ocalli", null, null, new ParametroId(75), 3, null),
            Parametro.Create(new ParametroId(133), "Ocumal", null, null, new ParametroId(75), 3, null),
            Parametro.Create(new ParametroId(134), "Pisuquia", null, null, new ParametroId(75), 3, null),
            Parametro.Create(new ParametroId(135), "Providencia", null, null, new ParametroId(75), 3, null),
            Parametro.Create(new ParametroId(136), "San Cristóbal", null, null, new ParametroId(75), 3, null),
            Parametro.Create(new ParametroId(137), "San Francisco de Yeso", null, null, new ParametroId(75), 3, null),
            Parametro.Create(new ParametroId(138), "San Jerónimo", null, null, new ParametroId(75), 3, null),
            Parametro.Create(new ParametroId(139), "San Juan de Lopecancha", null, null, new ParametroId(75), 3, null),
            Parametro.Create(new ParametroId(140), "Santa Catalina", null, null, new ParametroId(75), 3, null),
            Parametro.Create(new ParametroId(141), "Santo Tomas", null, null, new ParametroId(75), 3, null),
            Parametro.Create(new ParametroId(142), "Tingo", null, null, new ParametroId(75), 3, null),
            Parametro.Create(new ParametroId(143), "Trita", null, null, new ParametroId(75), 3, null),
            Parametro.Create(new ParametroId(144), "San Nicolás", null, null, new ParametroId(76), 3, null),
            Parametro.Create(new ParametroId(145), "Chirimoto", null, null, new ParametroId(76), 3, null),
            Parametro.Create(new ParametroId(146), "Cochamal", null, null, new ParametroId(76), 3, null),
            Parametro.Create(new ParametroId(147), "Huambo", null, null, new ParametroId(76), 3, null),
            Parametro.Create(new ParametroId(148), "Limabamba", null, null, new ParametroId(76), 3, null),
            Parametro.Create(new ParametroId(149), "Longar", null, null, new ParametroId(76), 3, null),
            Parametro.Create(new ParametroId(150), "Mariscal Benavides", null, null, new ParametroId(76), 3, null),
            Parametro.Create(new ParametroId(151), "Milpuc", null, null, new ParametroId(76), 3, null),
            Parametro.Create(new ParametroId(152), "Omia", null, null, new ParametroId(76), 3, null),
            Parametro.Create(new ParametroId(153), "Santa Rosa", null, null, new ParametroId(76), 3, null),
            Parametro.Create(new ParametroId(154), "Totora", null, null, new ParametroId(76), 3, null),
            Parametro.Create(new ParametroId(155), "Vista Alegre", null, null, new ParametroId(76), 3, null),
            Parametro.Create(new ParametroId(156), "Bagua Grande", null, null, new ParametroId(77), 3, null),
            Parametro.Create(new ParametroId(157), "Cajaruro", null, null, new ParametroId(77), 3, null),
            Parametro.Create(new ParametroId(158), "Cumba", null, null, new ParametroId(77), 3, null),
            Parametro.Create(new ParametroId(159), "El Milagro", null, null, new ParametroId(77), 3, null),
            Parametro.Create(new ParametroId(160), "Jamalca", null, null, new ParametroId(77), 3, null),
            Parametro.Create(new ParametroId(161), "Lonya Grande", null, null, new ParametroId(77), 3, null),
            Parametro.Create(new ParametroId(162), "Yamon", null, null, new ParametroId(77), 3, null),

            //Ancash
            //Provincias
            Parametro.Create(new ParametroId(163), "Huaraz", null, null, new ParametroId(26), 2, null),
            Parametro.Create(new ParametroId(164), "Aija", null, null, new ParametroId(26), 2, null),
            Parametro.Create(new ParametroId(165), "Antonio Raymondi", null, null, new ParametroId(26), 2, null),
            Parametro.Create(new ParametroId(166), "Asunción", null, null, new ParametroId(26), 2, null),
            Parametro.Create(new ParametroId(167), "Bolognesi", null, null, new ParametroId(26), 2, null),
            Parametro.Create(new ParametroId(168), "Carhuaz", null, null, new ParametroId(26), 2, null),
            Parametro.Create(new ParametroId(169), "Carlos Fermín Fitzcarrald", null, null, new ParametroId(26), 2, null),
            Parametro.Create(new ParametroId(170), "Casma", null, null, new ParametroId(26), 2, null),
            Parametro.Create(new ParametroId(171), "Corongo", null, null, new ParametroId(26), 2, null),
            Parametro.Create(new ParametroId(172), "Huari", null, null, new ParametroId(26), 2, null),
            Parametro.Create(new ParametroId(173), "Huarmey", null, null, new ParametroId(26), 2, null),
            Parametro.Create(new ParametroId(174), "Huaylas", null, null, new ParametroId(26), 2, null),
            Parametro.Create(new ParametroId(175), "Mariscal Luzuriaga", null, null, new ParametroId(26), 2, null),
            Parametro.Create(new ParametroId(176), "Ocros", null, null, new ParametroId(26), 2, null),
            Parametro.Create(new ParametroId(177), "Pallasca", null, null, new ParametroId(26), 2, null),
            Parametro.Create(new ParametroId(178), "Pomabamba", null, null, new ParametroId(26), 2, null),
            Parametro.Create(new ParametroId(179), "Recuay", null, null, new ParametroId(26), 2, null),
            Parametro.Create(new ParametroId(180), "Santa", null, null, new ParametroId(26), 2, null),
            Parametro.Create(new ParametroId(181), "Sihuas", null, null, new ParametroId(26), 2, null),
            Parametro.Create(new ParametroId(182), "Yungay", null, null, new ParametroId(26), 2, null),

            //Distritos
            Parametro.Create(new ParametroId(183), "Huaraz", null, null, new ParametroId(163), 3, null),
            Parametro.Create(new ParametroId(184), "Cochabamba", null, null, new ParametroId(163), 3, null),
            Parametro.Create(new ParametroId(185), "Colcabamba", null, null, new ParametroId(163), 3, null),
            Parametro.Create(new ParametroId(186), "Huanchay", null, null, new ParametroId(163), 3, null),
            Parametro.Create(new ParametroId(187), "Independencia", null, null, new ParametroId(163), 3, null),
            Parametro.Create(new ParametroId(188), "Jangas", null, null, new ParametroId(163), 3, null),
            Parametro.Create(new ParametroId(189), "La Libertad", null, null, new ParametroId(163), 3, null),
            Parametro.Create(new ParametroId(190), "Olleros", null, null, new ParametroId(163), 3, null),
            Parametro.Create(new ParametroId(191), "Pampas Grande", null, null, new ParametroId(163), 3, null),
            Parametro.Create(new ParametroId(192), "Pariacoto", null, null, new ParametroId(163), 3, null),
            Parametro.Create(new ParametroId(193), "Pira", null, null, new ParametroId(163), 3, null),
            Parametro.Create(new ParametroId(194), "Tarica", null, null, new ParametroId(163), 3, null),
            Parametro.Create(new ParametroId(195), "Aija", null, null, new ParametroId(164), 3, null),
            Parametro.Create(new ParametroId(196), "Aija", null, null, new ParametroId(164), 3, null),
            Parametro.Create(new ParametroId(197), "Coris", null, null, new ParametroId(164), 3, null),
            Parametro.Create(new ParametroId(198), "Huacllan", null, null, new ParametroId(164), 3, null),
            Parametro.Create(new ParametroId(199), "La Merced", null, null, new ParametroId(164), 3, null),
            Parametro.Create(new ParametroId(200), "Succha", null, null, new ParametroId(164), 3, null),
            Parametro.Create(new ParametroId(201), "Llamellin", null, null, new ParametroId(165), 3, null),
            Parametro.Create(new ParametroId(202), "Aczo", null, null, new ParametroId(165), 3, null),
            Parametro.Create(new ParametroId(203), "Chaccho", null, null, new ParametroId(165), 3, null),
            Parametro.Create(new ParametroId(204), "Chingas", null, null, new ParametroId(165), 3, null),
            Parametro.Create(new ParametroId(205), "Mirgas", null, null, new ParametroId(165), 3, null),
            Parametro.Create(new ParametroId(206), "San Juan de Rontoy", null, null, new ParametroId(165), 3, null),
            Parametro.Create(new ParametroId(207), "Chacas", null, null, new ParametroId(166), 3, null),
            Parametro.Create(new ParametroId(208), "Acochaca", null, null, new ParametroId(166), 3, null),
            Parametro.Create(new ParametroId(209), "Chiquian", null, null, new ParametroId(167), 3, null),
            Parametro.Create(new ParametroId(210), "Abelardo Pardo Lezameta", null, null, new ParametroId(167), 3, null),
            Parametro.Create(new ParametroId(211), "Antonio Raymondi", null, null, new ParametroId(167), 3, null),
            Parametro.Create(new ParametroId(212), "Aquia", null, null, new ParametroId(167), 3, null),
            Parametro.Create(new ParametroId(213), "Cajacay", null, null, new ParametroId(167), 3, null),
            Parametro.Create(new ParametroId(214), "Canis", null, null, new ParametroId(167), 3, null),
            Parametro.Create(new ParametroId(215), "Colquioc", null, null, new ParametroId(167), 3, null),
            Parametro.Create(new ParametroId(216), "Huallanca", null, null, new ParametroId(167), 3, null),
            Parametro.Create(new ParametroId(217), "Huasta", null, null, new ParametroId(167), 3, null),
            Parametro.Create(new ParametroId(218), "Huayllacayan", null, null, new ParametroId(167), 3, null),
            Parametro.Create(new ParametroId(219), "La Primavera", null, null, new ParametroId(167), 3, null),
            Parametro.Create(new ParametroId(220), "Mangas", null, null, new ParametroId(167), 3, null),
            Parametro.Create(new ParametroId(221), "Pacllon", null, null, new ParametroId(167), 3, null),
            Parametro.Create(new ParametroId(222), "San Miguel de Corpanqui", null, null, new ParametroId(167), 3, null),
            Parametro.Create(new ParametroId(223), "Ticllos", null, null, new ParametroId(167), 3, null),
            Parametro.Create(new ParametroId(224), "Carhuaz", null, null, new ParametroId(168), 3, null),
            Parametro.Create(new ParametroId(225), "Carhuaz", null, null, new ParametroId(168), 3, null),
            Parametro.Create(new ParametroId(226), "Acopampa", null, null, new ParametroId(168), 3, null),
            Parametro.Create(new ParametroId(227), "Amashca", null, null, new ParametroId(168), 3, null),
            Parametro.Create(new ParametroId(228), "Anta", null, null, new ParametroId(168), 3, null),
            Parametro.Create(new ParametroId(229), "Ataquero", null, null, new ParametroId(168), 3, null),
            Parametro.Create(new ParametroId(230), "Marcara", null, null, new ParametroId(168), 3, null),
            Parametro.Create(new ParametroId(231), "Pariahuanca", null, null, new ParametroId(168), 3, null),
            Parametro.Create(new ParametroId(232), "San Miguel de Aco", null, null, new ParametroId(168), 3, null),
            Parametro.Create(new ParametroId(233), "Shilla", null, null, new ParametroId(168), 3, null),
            Parametro.Create(new ParametroId(234), "Tinco", null, null, new ParametroId(168), 3, null),
            Parametro.Create(new ParametroId(235), "Yungar", null, null, new ParametroId(168), 3, null),
            Parametro.Create(new ParametroId(236), "San Luis", null, null, new ParametroId(169), 3, null),
            Parametro.Create(new ParametroId(237), "San Nicolás", null, null, new ParametroId(169), 3, null),
            Parametro.Create(new ParametroId(238), "Yauya", null, null, new ParametroId(169), 3, null),
            Parametro.Create(new ParametroId(239), "Casma", null, null, new ParametroId(170), 3, null),
            Parametro.Create(new ParametroId(240), "Buena Vista Alta", null, null, new ParametroId(170), 3, null),
            Parametro.Create(new ParametroId(241), "Comandante Noel", null, null, new ParametroId(170), 3, null),
            Parametro.Create(new ParametroId(242), "Yautan", null, null, new ParametroId(170), 3, null),
            Parametro.Create(new ParametroId(243), "Corongo", null, null, new ParametroId(171), 3, null),
            Parametro.Create(new ParametroId(244), "Aco", null, null, new ParametroId(171), 3, null),
            Parametro.Create(new ParametroId(245), "Bambas", null, null, new ParametroId(171), 3, null),
            Parametro.Create(new ParametroId(246), "Cusca", null, null, new ParametroId(171), 3, null),
            Parametro.Create(new ParametroId(247), "La Pampa", null, null, new ParametroId(171), 3, null),
            Parametro.Create(new ParametroId(248), "Yanac", null, null, new ParametroId(171), 3, null),
            Parametro.Create(new ParametroId(249), "Yupan", null, null, new ParametroId(171), 3, null),
            Parametro.Create(new ParametroId(250), "Huari", null, null, new ParametroId(172), 3, null),
            Parametro.Create(new ParametroId(251), "Anra", null, null, new ParametroId(172), 3, null),
            Parametro.Create(new ParametroId(252), "Cajay", null, null, new ParametroId(172), 3, null),
            Parametro.Create(new ParametroId(253), "Chavin de Huantar", null, null, new ParametroId(172), 3, null),
            Parametro.Create(new ParametroId(254), "Huacachi", null, null, new ParametroId(172), 3, null),
            Parametro.Create(new ParametroId(255), "Huacchis", null, null, new ParametroId(172), 3, null),
            Parametro.Create(new ParametroId(256), "Huachis", null, null, new ParametroId(172), 3, null),
            Parametro.Create(new ParametroId(257), "Huantar", null, null, new ParametroId(172), 3, null),
            Parametro.Create(new ParametroId(258), "Masin", null, null, new ParametroId(172), 3, null),
            Parametro.Create(new ParametroId(259), "Paucas", null, null, new ParametroId(172), 3, null),
            Parametro.Create(new ParametroId(260), "Ponto", null, null, new ParametroId(172), 3, null),
            Parametro.Create(new ParametroId(261), "Rahuapampa", null, null, new ParametroId(172), 3, null),
            Parametro.Create(new ParametroId(262), "Rapayan", null, null, new ParametroId(172), 3, null),
            Parametro.Create(new ParametroId(263), "San Marcos", null, null, new ParametroId(172), 3, null),
            Parametro.Create(new ParametroId(264), "San Pedro de Chana", null, null, new ParametroId(172), 3, null),
            Parametro.Create(new ParametroId(265), "Uco", null, null, new ParametroId(172), 3, null),
            Parametro.Create(new ParametroId(266), "Huarmey", null, null, new ParametroId(173), 3, null),
            Parametro.Create(new ParametroId(267), "Cochapeti", null, null, new ParametroId(173), 3, null),
            Parametro.Create(new ParametroId(268), "Culebras", null, null, new ParametroId(173), 3, null),
            Parametro.Create(new ParametroId(269), "Huayan", null, null, new ParametroId(173), 3, null),
            Parametro.Create(new ParametroId(270), "Malvas", null, null, new ParametroId(173), 3, null),
            Parametro.Create(new ParametroId(271), "Caraz", null, null, new ParametroId(174), 3, null),
            Parametro.Create(new ParametroId(272), "Huallanca", null, null, new ParametroId(174), 3, null),
            Parametro.Create(new ParametroId(273), "Huata", null, null, new ParametroId(174), 3, null),
            Parametro.Create(new ParametroId(274), "Huaylas", null, null, new ParametroId(174), 3, null),
            Parametro.Create(new ParametroId(275), "Mato", null, null, new ParametroId(174), 3, null),
            Parametro.Create(new ParametroId(276), "Pamparomas", null, null, new ParametroId(174), 3, null),
            Parametro.Create(new ParametroId(277), "Pueblo Libre", null, null, new ParametroId(174), 3, null),
            Parametro.Create(new ParametroId(278), "Santa Cruz", null, null, new ParametroId(174), 3, null),
            Parametro.Create(new ParametroId(279), "Santo Toribio", null, null, new ParametroId(174), 3, null),
            Parametro.Create(new ParametroId(280), "Yuracmarca", null, null, new ParametroId(174), 3, null),
            Parametro.Create(new ParametroId(281), "Piscobamba", null, null, new ParametroId(175), 3, null),
            Parametro.Create(new ParametroId(282), "Casca", null, null, new ParametroId(175), 3, null),
            Parametro.Create(new ParametroId(283), "Eleazar Guzmán Barron", null, null, new ParametroId(175), 3, null),
            Parametro.Create(new ParametroId(284), "Fidel Olivas Escudero", null, null, new ParametroId(175), 3, null),
            Parametro.Create(new ParametroId(285), "Llama", null, null, new ParametroId(175), 3, null),
            Parametro.Create(new ParametroId(286), "Llumpa", null, null, new ParametroId(175), 3, null),
            Parametro.Create(new ParametroId(287), "Lucma", null, null, new ParametroId(175), 3, null),
            Parametro.Create(new ParametroId(288), "Musga", null, null, new ParametroId(175), 3, null),
            Parametro.Create(new ParametroId(289), "Ocros", null, null, new ParametroId(176), 3, null),
            Parametro.Create(new ParametroId(290), "Acas", null, null, new ParametroId(176), 3, null),
            Parametro.Create(new ParametroId(291), "Cajamarquilla", null, null, new ParametroId(176), 3, null),
            Parametro.Create(new ParametroId(292), "Carhuapampa", null, null, new ParametroId(176), 3, null),
            Parametro.Create(new ParametroId(293), "Cochas", null, null, new ParametroId(176), 3, null),
            Parametro.Create(new ParametroId(294), "Congas", null, null, new ParametroId(176), 3, null),
            Parametro.Create(new ParametroId(295), "Llipa", null, null, new ParametroId(176), 3, null),
            Parametro.Create(new ParametroId(296), "San Cristóbal de Rajan", null, null, new ParametroId(176), 3, null),
            Parametro.Create(new ParametroId(297), "San Pedro", null, null, new ParametroId(176), 3, null),
            Parametro.Create(new ParametroId(298), "Santiago de Chilcas", null, null, new ParametroId(176), 3, null),
            Parametro.Create(new ParametroId(299), "Cabana", null, null, new ParametroId(177), 3, null),
            Parametro.Create(new ParametroId(300), "Bolognesi", null, null, new ParametroId(177), 3, null),
            Parametro.Create(new ParametroId(301), "Conchucos", null, null, new ParametroId(177), 3, null),
            Parametro.Create(new ParametroId(302), "Huacaschuque", null, null, new ParametroId(177), 3, null),
            Parametro.Create(new ParametroId(303), "Huandoval", null, null, new ParametroId(177), 3, null),
            Parametro.Create(new ParametroId(304), "Lacabamba", null, null, new ParametroId(177), 3, null),
            Parametro.Create(new ParametroId(305), "Llapo", null, null, new ParametroId(177), 3, null),
            Parametro.Create(new ParametroId(306), "Pallasca", null, null, new ParametroId(177), 3, null),
            Parametro.Create(new ParametroId(307), "Pampas", null, null, new ParametroId(177), 3, null),
            Parametro.Create(new ParametroId(308), "Santa Rosa", null, null, new ParametroId(177), 3, null),
            Parametro.Create(new ParametroId(309), "Tauca", null, null, new ParametroId(177), 3, null),
            Parametro.Create(new ParametroId(310), "Pomabamba", null, null, new ParametroId(178), 3, null),
            Parametro.Create(new ParametroId(311), "Huayllan", null, null, new ParametroId(178), 3, null),
            Parametro.Create(new ParametroId(312), "Parobamba", null, null, new ParametroId(178), 3, null),
            Parametro.Create(new ParametroId(313), "Quinuabamba", null, null, new ParametroId(178), 3, null),
            Parametro.Create(new ParametroId(314), "Recuay", null, null, new ParametroId(179), 3, null),
            Parametro.Create(new ParametroId(315), "Catac", null, null, new ParametroId(179), 3, null),
            Parametro.Create(new ParametroId(316), "Cotaparaco", null, null, new ParametroId(179), 3, null),
            Parametro.Create(new ParametroId(317), "Huayllapampa", null, null, new ParametroId(179), 3, null),
            Parametro.Create(new ParametroId(318), "Llacllin", null, null, new ParametroId(179), 3, null),
            Parametro.Create(new ParametroId(319), "Marca", null, null, new ParametroId(179), 3, null),
            Parametro.Create(new ParametroId(320), "Pampas Chico", null, null, new ParametroId(179), 3, null),
            Parametro.Create(new ParametroId(321), "Pararin", null, null, new ParametroId(179), 3, null),
            Parametro.Create(new ParametroId(322), "Tapacocha", null, null, new ParametroId(179), 3, null),
            Parametro.Create(new ParametroId(323), "Ticapampa", null, null, new ParametroId(179), 3, null),
            Parametro.Create(new ParametroId(324), "Chimbote", null, null, new ParametroId(180), 3, null),
            Parametro.Create(new ParametroId(325), "Cáceres del Perú", null, null, new ParametroId(180), 3, null),
            Parametro.Create(new ParametroId(326), "Coishco", null, null, new ParametroId(180), 3, null),
            Parametro.Create(new ParametroId(327), "Macate", null, null, new ParametroId(180), 3, null),
            Parametro.Create(new ParametroId(328), "Moro", null, null, new ParametroId(180), 3, null),
            Parametro.Create(new ParametroId(329), "Nepeña", null, null, new ParametroId(180), 3, null),
            Parametro.Create(new ParametroId(330), "Samanco", null, null, new ParametroId(180), 3, null),
            Parametro.Create(new ParametroId(331), "Santa", null, null, new ParametroId(180), 3, null),
            Parametro.Create(new ParametroId(332), "Nuevo Chimbote", null, null, new ParametroId(180), 3, null),
            Parametro.Create(new ParametroId(333), "Sihuas", null, null, new ParametroId(181), 3, null),
            Parametro.Create(new ParametroId(334), "Acobamba", null, null, new ParametroId(181), 3, null),
            Parametro.Create(new ParametroId(335), "Alfonso Ugarte", null, null, new ParametroId(181), 3, null),
            Parametro.Create(new ParametroId(336), "Cashapampa", null, null, new ParametroId(181), 3, null),
            Parametro.Create(new ParametroId(337), "Chingalpo", null, null, new ParametroId(181), 3, null),
            Parametro.Create(new ParametroId(338), "Huayllabamba", null, null, new ParametroId(181), 3, null),
            Parametro.Create(new ParametroId(339), "Quiches", null, null, new ParametroId(181), 3, null),
            Parametro.Create(new ParametroId(340), "Ragash", null, null, new ParametroId(181), 3, null),
            Parametro.Create(new ParametroId(341), "San Juan", null, null, new ParametroId(181), 3, null),
            Parametro.Create(new ParametroId(342), "Sicsibamba", null, null, new ParametroId(181), 3, null),
            Parametro.Create(new ParametroId(343), "Yungay", null, null, new ParametroId(182), 3, null),
            Parametro.Create(new ParametroId(344), "Cascapara", null, null, new ParametroId(182), 3, null),
            Parametro.Create(new ParametroId(345), "Mancos", null, null, new ParametroId(182), 3, null),
            Parametro.Create(new ParametroId(346), "Matacoto", null, null, new ParametroId(182), 3, null),
            Parametro.Create(new ParametroId(347), "Quillo", null, null, new ParametroId(182), 3, null),
            Parametro.Create(new ParametroId(348), "Ranrahirca", null, null, new ParametroId(182), 3, null),
            Parametro.Create(new ParametroId(349), "Shupluy", null, null, new ParametroId(182), 3, null),
            Parametro.Create(new ParametroId(350), "Yanama", null, null, new ParametroId(182), 3, null)





















        );
    }
}