// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MsAcceso.Infrastructure;

#nullable disable

namespace MsAcceso.Infrastructure.Migrations.LicenciaDb
{
    [DbContext(typeof(LicenciaDbContext))]
    partial class LicenciaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MsAcceso.Domain.Tenant.CarpetasPresupuestalesTenant.CarpetaPresupuestalTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<Guid?>("Dependencia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Dependencia");

                    b.ToTable("carpetas_presupuestales", (string)null);
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.ClientesTenant.ClienteTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TipoClienteId")
                        .HasColumnType("int");

                    b.Property<int?>("TipoDocumentoId")
                        .HasColumnType("int");

                    b.Property<int?>("TipoPersonaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.EspecialidadesTenant.EspecialidadTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ProyectoTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoTenantId");

                    b.ToTable("especialidades", (string)null);
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.PartidasRecursosTenant.PartidaRecursoTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("Cantidad")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Cuadrilla")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<double?>("Parcial")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<Guid>("PartidaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Precio")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<Guid>("RecursoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PartidaId");

                    b.HasIndex("RecursoId");

                    b.ToTable("partida_recurso", (string)null);
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.PartidasTenant.PartidaTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Correlativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Dependencia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Dependencia");

                    b.ToTable("partidas", (string)null);
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.PresupuestosEspecialidadTitulosPartidasRecursosTenant.PresupuestoEspecialidadTituloPartidaRecursoTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("Cantidad")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Cuadrilla")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<double?>("Parcial")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<double?>("Precio")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<Guid>("PresupuestoEspecialidadTituloPartidaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecursoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PresupuestoEspecialidadTituloPartidaId");

                    b.HasIndex("RecursoId");

                    b.ToTable("presupuestos_especialidad_titulos_partidas_recursos", (string)null);
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.PresupuestosEspecialidadTitulosPartidasTenant.PresupuestoEspecialidadTituloPartidaTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<Guid>("PartidaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PresupuestoEspecialidadTituloId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PartidaId");

                    b.HasIndex("PresupuestoEspecialidadTituloId");

                    b.ToTable("presupuestos_especialidad_titulos_partidas", (string)null);
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.PresupuestosEspecialidadTitulosTenant.PresupuestoEspecialidadTituloTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Correlativo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("Dependencia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EspecialidadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Nivel")
                        .HasColumnType("int");

                    b.Property<Guid?>("TituloId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Dependencia");

                    b.HasIndex("EspecialidadId");

                    b.HasIndex("TituloId");

                    b.ToTable("presupuestos_especialidad_titulos", (string)null);
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.PresupuestosTenant.PresupuestoTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<Guid?>("CarpetaPresupuestalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("DistritoId")
                        .HasColumnType("int");

                    b.Property<string>("Fecha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JornadaDiariaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("MonedaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Plazodias")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<double?>("PresupuestoBaseCD")
                        .HasColumnType("float");

                    b.Property<double?>("PresupuestoBaseDI")
                        .HasColumnType("float");

                    b.Property<double?>("PresupuestoOfertaCD")
                        .HasColumnType("float");

                    b.Property<double?>("PresupuestoOfertaDI")
                        .HasColumnType("float");

                    b.Property<int?>("ProvinciaId")
                        .HasColumnType("int");

                    b.Property<double?>("TotalPresupuestoBase")
                        .HasColumnType("float");

                    b.Property<double?>("TotalPresupuestoOferta")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CarpetaPresupuestalId");

                    b.HasIndex("ClienteId");

                    b.ToTable("presupuestos", (string)null);
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.ProyectosTenant.ProyectoTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Correlativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PresupuestoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PresupuestoId")
                        .IsUnique()
                        .HasFilter("[PresupuestoId] IS NOT NULL");

                    b.ToTable("proyectos", (string)null);
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.RecursosTenant.RecursoTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UnidadMedidaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("recursos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d3b9cc39-3942-45b4-8aab-02160c2867ab"),
                            Activo = true,
                            Nombre = "Capataz",
                            UnidadMedidaId = 2125
                        },
                        new
                        {
                            Id = new Guid("eb582231-35ff-4851-9ffc-fbbb7817819b"),
                            Activo = true,
                            Nombre = "Operador de maquinaria",
                            UnidadMedidaId = 2136
                        },
                        new
                        {
                            Id = new Guid("f8d324c2-5796-4468-9699-9dffe2fc96b2"),
                            Activo = true,
                            Nombre = "Supervisor de obra",
                            UnidadMedidaId = 2136
                        },
                        new
                        {
                            Id = new Guid("d2f71cc4-d0b4-41bf-a8b1-5049ea4b24ed"),
                            Activo = true,
                            Nombre = "Técnico eléctrico",
                            UnidadMedidaId = 2134
                        },
                        new
                        {
                            Id = new Guid("b8cf5bdb-8664-45cd-94ca-8b4f32836ac9"),
                            Activo = true,
                            Nombre = "Albañil",
                            UnidadMedidaId = 2136
                        },
                        new
                        {
                            Id = new Guid("8cb9f863-88a4-48a5-9b61-bde441eedbdb"),
                            Activo = true,
                            Nombre = "Ayudante general",
                            UnidadMedidaId = 2136
                        },
                        new
                        {
                            Id = new Guid("c48b85f4-137e-45b7-bbbb-f7deee44b60e"),
                            Activo = true,
                            Nombre = "Cemento",
                            UnidadMedidaId = 2126
                        },
                        new
                        {
                            Id = new Guid("4c8622c8-738d-4018-b21d-ce7f92f8285a"),
                            Activo = true,
                            Nombre = "Arena",
                            UnidadMedidaId = 2131
                        },
                        new
                        {
                            Id = new Guid("5d2b240e-41bb-4010-81b0-e26a12e13fe7"),
                            Activo = true,
                            Nombre = "Grava",
                            UnidadMedidaId = 2131
                        },
                        new
                        {
                            Id = new Guid("7b11675e-d66a-4975-8af4-ff7f2cc51e7c"),
                            Activo = true,
                            Nombre = "Bloques de concreto",
                            UnidadMedidaId = 2125
                        },
                        new
                        {
                            Id = new Guid("9b102b9e-fd1b-4510-a5f5-9c8418caebca"),
                            Activo = true,
                            Nombre = "Ladrillos",
                            UnidadMedidaId = 2125
                        },
                        new
                        {
                            Id = new Guid("9255f3cd-9035-4dc4-9648-162b76708e21"),
                            Activo = true,
                            Nombre = "Varillas de acero",
                            UnidadMedidaId = 2132
                        },
                        new
                        {
                            Id = new Guid("d8520aed-4613-4b81-9826-3f620291347a"),
                            Activo = true,
                            Nombre = "Tubos de PVC",
                            UnidadMedidaId = 2132
                        },
                        new
                        {
                            Id = new Guid("fc35c5f1-bad1-4b20-b3a6-3a805017c1d1"),
                            Activo = true,
                            Nombre = "Pintura",
                            UnidadMedidaId = 2129
                        },
                        new
                        {
                            Id = new Guid("6f4d15a7-28fa-4f30-8e70-473b6f2b8d55"),
                            Activo = true,
                            Nombre = "Yeso",
                            UnidadMedidaId = 2126
                        },
                        new
                        {
                            Id = new Guid("2ba93433-d164-47c1-95cc-44f0fea1f76c"),
                            Activo = true,
                            Nombre = "Clavos",
                            UnidadMedidaId = 2125
                        },
                        new
                        {
                            Id = new Guid("591d827f-a6d3-427a-b563-f2ce1e2e4316"),
                            Activo = true,
                            Nombre = "Cables eléctricos",
                            UnidadMedidaId = 2132
                        },
                        new
                        {
                            Id = new Guid("bda725e2-8fdb-47fd-981c-c5aaaed7e10b"),
                            Activo = true,
                            Nombre = "Excavadora",
                            UnidadMedidaId = 2135
                        },
                        new
                        {
                            Id = new Guid("8e1fe177-ac6c-4822-8494-66966a28991b"),
                            Activo = true,
                            Nombre = "Camión de volteo",
                            UnidadMedidaId = 2139
                        },
                        new
                        {
                            Id = new Guid("2b9c348d-0f95-49ac-9fd4-50687fedb30c"),
                            Activo = true,
                            Nombre = "Compactadora",
                            UnidadMedidaId = 2135
                        },
                        new
                        {
                            Id = new Guid("eaa5355b-cd55-4f16-91d8-ed6e15e2696e"),
                            Activo = true,
                            Nombre = "Taladro eléctrico",
                            UnidadMedidaId = 2135
                        },
                        new
                        {
                            Id = new Guid("acfbebd7-4efb-4ebd-b000-8c9e93ed1d10"),
                            Activo = true,
                            Nombre = "Andamios",
                            UnidadMedidaId = 2125
                        },
                        new
                        {
                            Id = new Guid("32ab1623-b9fe-4352-8826-df2becefda31"),
                            Activo = true,
                            Nombre = "Martillos",
                            UnidadMedidaId = 2125
                        },
                        new
                        {
                            Id = new Guid("27aebd14-6b04-4368-8d21-dfbb6c32be37"),
                            Activo = true,
                            Nombre = "Llaves inglesas",
                            UnidadMedidaId = 2125
                        },
                        new
                        {
                            Id = new Guid("c01427d9-3e20-4e97-94f1-6731a521d8af"),
                            Activo = true,
                            Nombre = "Sierra eléctrica",
                            UnidadMedidaId = 2135
                        },
                        new
                        {
                            Id = new Guid("f1df947e-039d-4a57-b095-b7f1cae3a878"),
                            Activo = true,
                            Nombre = "Renta de camión",
                            UnidadMedidaId = 2139
                        },
                        new
                        {
                            Id = new Guid("3de59329-8cdd-4484-a782-133353a58868"),
                            Activo = true,
                            Nombre = "Flete de materiales",
                            UnidadMedidaId = 2139
                        },
                        new
                        {
                            Id = new Guid("97778eb3-f658-485b-a434-d97d1aca52b0"),
                            Activo = true,
                            Nombre = "Renta de grúa",
                            UnidadMedidaId = 2135
                        },
                        new
                        {
                            Id = new Guid("63e8892a-0d3a-4643-bcc6-348f8ce4422b"),
                            Activo = true,
                            Nombre = "Transporte personal",
                            UnidadMedidaId = 2137
                        },
                        new
                        {
                            Id = new Guid("e5879232-7e13-441b-8428-e63c6dff0964"),
                            Activo = true,
                            Nombre = "Electricidad",
                            UnidadMedidaId = 2136
                        },
                        new
                        {
                            Id = new Guid("72b7ba5e-a82e-464c-bb0b-c472fd0dc929"),
                            Activo = true,
                            Nombre = "Agua potable",
                            UnidadMedidaId = 2136
                        },
                        new
                        {
                            Id = new Guid("e42627c8-918b-4446-98fa-503ee1e18468"),
                            Activo = true,
                            Nombre = "Gas",
                            UnidadMedidaId = 2129
                        },
                        new
                        {
                            Id = new Guid("e5c17785-c01f-4049-8056-1ff4d71bcd9d"),
                            Activo = true,
                            Nombre = "Alquiler de oficinas",
                            UnidadMedidaId = 2137
                        },
                        new
                        {
                            Id = new Guid("4ca1e7b4-d6e0-4eef-aa39-af70dc63b62b"),
                            Activo = true,
                            Nombre = "Consultoría técnica",
                            UnidadMedidaId = 2136
                        },
                        new
                        {
                            Id = new Guid("876061f6-2116-422a-8dae-81780fc0c6c9"),
                            Activo = true,
                            Nombre = "Supervisión de obra externa",
                            UnidadMedidaId = 2136
                        },
                        new
                        {
                            Id = new Guid("52f0dc91-4a8c-4406-b715-c4c91629c70a"),
                            Activo = true,
                            Nombre = "Seguridad en obra",
                            UnidadMedidaId = 2136
                        },
                        new
                        {
                            Id = new Guid("b70043fa-dbdc-4e08-a5bb-a66b85766f77"),
                            Activo = true,
                            Nombre = "Equipo de protección personal",
                            UnidadMedidaId = 2125
                        },
                        new
                        {
                            Id = new Guid("29ff03d7-c367-49dc-99de-f8194a954e9f"),
                            Activo = true,
                            Nombre = "Polvo de mármol",
                            UnidadMedidaId = 2126
                        },
                        new
                        {
                            Id = new Guid("181bd9ce-1edb-4e84-959a-1eb23c2f19a4"),
                            Activo = true,
                            Nombre = "Madera para cimbra",
                            UnidadMedidaId = 2132
                        },
                        new
                        {
                            Id = new Guid("c4b91d25-4d10-4d4e-96f3-f33b5bcc6e33"),
                            Activo = true,
                            Nombre = "Lonas protectoras",
                            UnidadMedidaId = 2125
                        },
                        new
                        {
                            Id = new Guid("d939ef8c-975f-4006-9061-f61b883ec407"),
                            Activo = true,
                            Nombre = "Seguro de maquinaria",
                            UnidadMedidaId = 2137
                        });
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.TitulosTenant.TituloTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("titulos", (string)null);
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.CarpetasPresupuestalesTenant.CarpetaPresupuestalTenant", b =>
                {
                    b.HasOne("MsAcceso.Domain.Tenant.CarpetasPresupuestalesTenant.CarpetaPresupuestalTenant", "DependenciaModel")
                        .WithMany("CarpetasPresupuestales")
                        .HasForeignKey("Dependencia");

                    b.Navigation("DependenciaModel");
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.EspecialidadesTenant.EspecialidadTenant", b =>
                {
                    b.HasOne("MsAcceso.Domain.Tenant.ProyectosTenant.ProyectoTenant", "ProyectoTenant")
                        .WithMany("Especialidades")
                        .HasForeignKey("ProyectoTenantId");

                    b.Navigation("ProyectoTenant");
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.PartidasRecursosTenant.PartidaRecursoTenant", b =>
                {
                    b.HasOne("MsAcceso.Domain.Tenant.PartidasTenant.PartidaTenant", "Partida")
                        .WithMany("PartidasRecursos")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MsAcceso.Domain.Tenant.RecursosTenant.RecursoTenant", "Recurso")
                        .WithMany()
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partida");

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.PartidasTenant.PartidaTenant", b =>
                {
                    b.HasOne("MsAcceso.Domain.Tenant.PartidasTenant.PartidaTenant", "DependenciaModel")
                        .WithMany("Partidas")
                        .HasForeignKey("Dependencia");

                    b.Navigation("DependenciaModel");
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.PresupuestosEspecialidadTitulosPartidasRecursosTenant.PresupuestoEspecialidadTituloPartidaRecursoTenant", b =>
                {
                    b.HasOne("MsAcceso.Domain.Tenant.PresupuestosEspecialidadTitulosPartidasTenant.PresupuestoEspecialidadTituloPartidaTenant", "PresupuestoEspecialidadTituloPartida")
                        .WithMany()
                        .HasForeignKey("PresupuestoEspecialidadTituloPartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MsAcceso.Domain.Tenant.RecursosTenant.RecursoTenant", "Recurso")
                        .WithMany("PresupuestosEspecialidadesTitulosPartidasRecursos")
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PresupuestoEspecialidadTituloPartida");

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.PresupuestosEspecialidadTitulosPartidasTenant.PresupuestoEspecialidadTituloPartidaTenant", b =>
                {
                    b.HasOne("MsAcceso.Domain.Tenant.PartidasTenant.PartidaTenant", "Partida")
                        .WithMany("PresupuestosEspecialidadesTitulosPartidas")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MsAcceso.Domain.Tenant.PresupuestosEspecialidadTitulosTenant.PresupuestoEspecialidadTituloTenant", "PresupuestoEspecialidadTitulo")
                        .WithMany("PresupuestosEspecialidadTituloPartidas")
                        .HasForeignKey("PresupuestoEspecialidadTituloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partida");

                    b.Navigation("PresupuestoEspecialidadTitulo");
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.PresupuestosEspecialidadTitulosTenant.PresupuestoEspecialidadTituloTenant", b =>
                {
                    b.HasOne("MsAcceso.Domain.Tenant.PresupuestosEspecialidadTitulosTenant.PresupuestoEspecialidadTituloTenant", "DependenciaModel")
                        .WithMany("PresupuestosEspecialidadTitulos")
                        .HasForeignKey("Dependencia");

                    b.HasOne("MsAcceso.Domain.Tenant.EspecialidadesTenant.EspecialidadTenant", "Especialidad")
                        .WithMany("PresupuestosEspecialidadTitulos")
                        .HasForeignKey("EspecialidadId");

                    b.HasOne("MsAcceso.Domain.Tenant.TitulosTenant.TituloTenant", "Titulo")
                        .WithMany("PresupuestosEspecialidadesTitulos")
                        .HasForeignKey("TituloId");

                    b.Navigation("DependenciaModel");

                    b.Navigation("Especialidad");

                    b.Navigation("Titulo");
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.PresupuestosTenant.PresupuestoTenant", b =>
                {
                    b.HasOne("MsAcceso.Domain.Tenant.CarpetasPresupuestalesTenant.CarpetaPresupuestalTenant", "CarpetaPresupuestal")
                        .WithMany()
                        .HasForeignKey("CarpetaPresupuestalId");

                    b.HasOne("MsAcceso.Domain.Tenant.ClientesTenant.ClienteTenant", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.Navigation("CarpetaPresupuestal");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.ProyectosTenant.ProyectoTenant", b =>
                {
                    b.HasOne("MsAcceso.Domain.Tenant.PresupuestosTenant.PresupuestoTenant", "Presupuesto")
                        .WithOne("ProyectoTenant")
                        .HasForeignKey("MsAcceso.Domain.Tenant.ProyectosTenant.ProyectoTenant", "PresupuestoId");

                    b.Navigation("Presupuesto");
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.CarpetasPresupuestalesTenant.CarpetaPresupuestalTenant", b =>
                {
                    b.Navigation("CarpetasPresupuestales");
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.EspecialidadesTenant.EspecialidadTenant", b =>
                {
                    b.Navigation("PresupuestosEspecialidadTitulos");
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.PartidasTenant.PartidaTenant", b =>
                {
                    b.Navigation("Partidas");

                    b.Navigation("PartidasRecursos");

                    b.Navigation("PresupuestosEspecialidadesTitulosPartidas");
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.PresupuestosEspecialidadTitulosTenant.PresupuestoEspecialidadTituloTenant", b =>
                {
                    b.Navigation("PresupuestosEspecialidadTituloPartidas");

                    b.Navigation("PresupuestosEspecialidadTitulos");
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.PresupuestosTenant.PresupuestoTenant", b =>
                {
                    b.Navigation("ProyectoTenant");
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.ProyectosTenant.ProyectoTenant", b =>
                {
                    b.Navigation("Especialidades");
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.RecursosTenant.RecursoTenant", b =>
                {
                    b.Navigation("PresupuestosEspecialidadesTitulosPartidasRecursos");
                });

            modelBuilder.Entity("MsAcceso.Domain.Tenant.TitulosTenant.TituloTenant", b =>
                {
                    b.Navigation("PresupuestosEspecialidadesTitulos");
                });
#pragma warning restore 612, 618
        }
    }
}
